spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true
  h2: # ② H2 콘솔 활성화
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 720150823291-mae0qve5bhmedl61jmibdve0ik8pm94c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot